In [1]:
import numpy as np

<h1 style="background-color:rgb(181 ,50 ,84);color:white;text-align:center">Lower triangular systems</h1>

$$x_1 = \frac{b_1}{l_{11}},\ \ \ \ \ \ \ x_i = \frac{1}{l_{11}}\bigg(b_i - \sum_{j = 1}^{i-1}l_{ij}x_j\bigg),\ \ \ \ \ \  \ \ i = 2,\dots,n$$


In [2]:
def forward_substitution(L: np.array, b: np.array) -> np.array:
    """ 
    Solves a lower triangular linear system using forward substitution
    
    Parameters:
        L (numpy array): lower triangular nxn matrix
        b (numpy array): nx1 known vector
        
    Returns:
        x (numpy array): nx1 vector solution of the linear system 
    """
    
    # Matrix dimensions
    n = L.shape[0]
    
    # Initalization of the solution vector
    x = np.zeros((n, 1))
    
    # First component
    x[0] = b[0] / L[0, 0]
    
    # Algorithm
    for i in range(1, n):
        x[i] = (b[i] - L[i, :i] @ x[:i]) / L[i, i]
        
    return x

### Testing

In [3]:
# Random linear system
L = np.random.randint(1, 20, (4, 4)) * np.tri(4, 4)
b = np.random.randint(1, 20, (4, 1))

# Solution of the system
x = forward_substitution(L, b)

# Residual vector
r = L @ x - b

# Print results
print(f'x = \n{x}\n')
print(f'r = \n{r}\n')

x = 
[[ 1.33333333]
 [-0.54166667]
 [ 0.47083333]
 [ 0.60833333]]

r = 
[[0.]
 [0.]
 [0.]
 [0.]]



<h1 style="background-color:rgb(181 ,50 ,84);color:white;text-align:center">Upper triangular system</h1>

$$x_n = \frac{b_n}{u_{nn}},\ \ \ \ \ \ \ x_i = \frac{1}{u_{ii}}\bigg(b_i - \sum_{j = i+1}^nu_{ij}x_j\bigg),\ \ \ \ \ \ \ i = n-1,\dots,1$$

In [4]:
def backward_substitution(U: np.array, b: np.array) -> np.array:
    """
    Solves an upper triangular linear system using backward substituion
    
    Parameters:
        U (numpy array): upper triangular nxn matrix
        b (numpy array): nx1 known vector
        
    Returns:
        x (numpy array): nx1 vector solution of the linear system 
    """
    
    # Matrix dimensions
    n = U.shape[0]
    
    # Initialization of the solution vector
    x = np.zeros((n, 1))
    
    # Last component
    x[n-1] = b[n-1] / U[n-1, n-1]
    
    # Algorithm
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - U[i, i+1:] @ x[i+1:]) / U[i, i]
    
    return x

### Testing

In [5]:
# Random linear system
U = np.random.randint(1, 20, (4, 4)) * np.tri(4, 4).T
b = np.random.randint(1, 20, (4, 1))

# Solution of the system
x = backward_substitution(U, b)

# Residual vector
r = U @ x - b

# Print results
print(f'x = \n{x}\n')
print(f'r = \n{r}\n')

x = 
[[ 5.50347222]
 [-9.41666667]
 [ 1.875     ]
 [ 1.5       ]]

r = 
[[0.]
 [0.]
 [0.]
 [0.]]

