In [1]:
import numpy as np

In [14]:
n = 7
m = 4

while np.linalg.matrix_rank(A := np.random.randint(1, 30, (n, m))) != m:
    pass

b = np.random.randint(1, 30, (n, 1))

<h1 style="background-color:rgb(181 ,50 ,84);color:white;text-align:center">Normal equations</h1>

In [15]:
# Cholesky factorization

# Decomposition
L = np.linalg.cholesky(A.T @ A)

# Ly = b
y = np.linalg.solve(L, A.T @ b)

# L^Tx = y
x = np.linalg.solve(L.T, y)

residual = np.linalg.norm(np.dot(A, x) - b)

lsq = np.linalg.lstsq(A, b, rcond=None)

print(f'Solution: x =\n{x}\n')
print(f'Residual: {residual}')
print(f'\nNumpy solution: \n{lsq[0]}')
print(f'\nNumpy residual: {np.sqrt(lsq[1][0])}')

Solution: x =
[[ 0.41126894]
 [ 0.1597151 ]
 [-0.04265094]
 [ 0.46484809]]

Residual: 14.975440490877448

Numpy solution: 
[[ 0.41126894]
 [ 0.1597151 ]
 [-0.04265094]
 [ 0.46484809]]

Numpy residual: 14.975440490877448


<h1 style="background-color:rgb(181 ,50 ,84);color:white;text-align:center">QR factorization</h1>

In [16]:
# QR factorization 
Q, R = np.linalg.qr(A)

x = np.linalg.inv(R) @ Q.T @ b
residual = np.linalg.norm(np.dot(A, x) - b)

lsq = np.linalg.lstsq(A, b, rcond=None)

print(f'Solution: x =\n{x}\n')
print(f'Residual: {residual}')
print(f'\nNumpy solution: \n{lsq[0]}')
print(f'\nNumpy residual: {np.sqrt(lsq[1][0])}')

Solution: x =
[[ 0.41126894]
 [ 0.1597151 ]
 [-0.04265094]
 [ 0.46484809]]

Residual: 14.975440490877446

Numpy solution: 
[[ 0.41126894]
 [ 0.1597151 ]
 [-0.04265094]
 [ 0.46484809]]

Numpy residual: 14.975440490877448
